"""Make nullable column

Revision ID: 9f49f1c44085
Revises: c9e62d6d03cf
Create Date: 2025-12-22 16:12:58.343162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f49f1c44085'
down_revision: Union[str, Sequence[str], None] = 'c9e62d6d03cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llms', 'tariff_method',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llms', 'tariff_method',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
