"""Add new columns in task

Revision ID: 1c0a2c44d96f
Revises: 101f8084597f
Create Date: 2026-01-14 16:01:07.636419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0a2c44d96f'
down_revision: Union[str, Sequence[str], None] = '101f8084597f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio_recognition_tasks', sa.Column('max_speakers_count', sa.Integer(), nullable=False))
    op.add_column('audio_recognition_tasks', sa.Column('output_document_ext', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audio_recognition_tasks', 'output_document_ext')
    op.drop_column('audio_recognition_tasks', 'max_speakers_count')
    # ### end Alembic commands ###
